server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?useSSL=false
    username: root
    password: kit
#  datasource:
#    name: test
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://localhost:3306/mybatis?useSSL=false
#    username: root
#    password: kit
#    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.jeor.hellossm.entity
  mapper-locations: classpath:mappers/*.xml
#logging:
#  level: debug
#  com.jeor.hellossm.mapper: debug